In [1]:
# Module 1 - Python & Data Science Fundamentals

print("Hello, Data Science!")
print("My name is Abhishek")
print("I am learning Python for Data Science")

Hello, Data Science!
My name is Abhishek
I am learning Python for Data Science

In [3]:
name = "Abhishek"
age = 20
course = "Data Science"

print("Name:", name)
print("Age:", age)
print("Course:", course)

Name: Abhishek
Age: 20
Course: Data Science

In [4]:
name = "Abhishek"       # String
age = 20                # Integer
height = 5.8            # Float
student = True          # Boolean

print(type(name))
print(type(age))
print(type(height))
print(type(student))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

In [5]:
a = 10
b = 3

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Power:", a ** b)

Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Floor Division: 3
Modulus: 1
Power: 1000

In [6]:
fruits = ["Apple", "Banana", "Mango", "Orange"]

print("Fruits:", fruits)
print("First fruit:", fruits[0])
print("Last fruit:", fruits[-1])

fruits.append("Grapes")
print("After adding:", fruits)

fruits.remove("Banana")
print("After removing:", fruits)

Fruits: ['Apple', 'Banana', 'Mango', 'Orange']
First fruit: Apple
Last fruit: Orange
After adding: ['Apple', 'Banana', 'Mango', 'Orange', 'Grapes']
After removing: ['Apple', 'Mango', 'Orange', 'Grapes']

In [7]:
student = {
    "name": "Abhishek",
    "age": 20,
    "course": "Data Science"
}

print("Student:", student)
print("Name:", student["name"])
print("Course:", student["course"])

Student: {'name': 'Abhishek', 'age': 20, 'course': 'Data Science'}
Name: Abhishek
Course: Data Science

In [8]:
numbers = [1, 2, 3, 4, 5]

for num in numbers:
    print(num)

1
2
3
4
5

In [9]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [10]:
numbers = [1, 2, 3, 4, 5]

for num in numbers:
    if num % 2 == 0:
        print(num, "is even")
    else:
        print(num, "is odd")

1 is odd
2 is even
3 is odd
4 is even
5 is odd

In [11]:
count = 1

while count <= 5:
    print("Count:", count)
    count = count + 1

Count: 1
Count: 2
Count: 3
Count: 4
Count: 5

In [12]:
for num in range(1, 21):
    if num % 3 == 0:
        print("Fizz")
    else:
        print(num)

1
2
Fizz
4
5
Fizz
7
8
Fizz
10
11
Fizz
13
14
Fizz
16
17
Fizz
19
20

In [13]:
def greet():
    print("Hello, Abhishek!")
    print("Welcome to Python for Data Science")

greet()

Hello, Abhishek!
Welcome to Python for Data Science

In [14]:
def add_numbers(a, b):
    result = a + b
    return result

answer = add_numbers(10, 20)
print("Sum:", answer)

Sum: 30

In [15]:
def check_number(num):
    if num % 2 == 0:
        return "Even"
    else:
        return "Odd"

print(check_number(10))
print(check_number(7))

Even
Odd

In [16]:
def calculate_average(a, b, c):
    average = (a + b + c) / 3
    return average

result = calculate_average(10, 20, 30)
print("Average:", result)

Average: 20.0

In [17]:
file = open("student.txt", "w")

file.write("Name: Abhishek\n")
file.write("Course: Data Science\n")
file.write("Learning Python")

file.close()

print("File created successfully!")

File created successfully!

In [18]:
file = open("student.txt", "r")

content = file.read()

print(content)

file.close()

Name: Abhishek
Course: Data Science
Learning Python

In [19]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print("Array:", numbers)
print("Sum:", np.sum(numbers))
print("Average:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Array: [10 20 30 40 50]
Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10

In [20]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]

In [21]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data)
print("Shape:", data.shape)
print("First row:", data[0])
print("First element:", data[0][0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
First row: [10 20 30]
First element: 10

In [22]:
import pandas as pd

data = {
    "Name": ["Abhishek", "Rahul", "Anil", "Priya"],
    "Age": [20, 21, 22, 20],
    "Marks": [85, 78, 92, 88]
}

df = pd.DataFrame(data)

print(df)

       Name  Age  Marks
0  Abhishek   20     85
1     Rahul   21     78
2      Anil   22     92
3     Priya   20     88

In [23]:
print(df.head())

       Name  Age  Marks
0  Abhishek   20     85
1     Rahul   21     78
2      Anil   22     92
3     Priya   20     88

In [24]:
print(df["Name"])
print(df["Marks"])

0    Abhishek
1       Rahul
2        Anil
3       Priya
Name: Name, dtype: object
0    85
1    78
2    92
3    88
Name: Marks, dtype: int64

In [25]:
print("Average Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

Average Marks: 85.75
Highest Marks: 92
Lowest Marks: 78

In [26]:
df["Pass"] = df["Marks"] >= 40

print(df)

       Name  Age  Marks  Pass
0  Abhishek   20     85  True
1     Rahul   21     78  True
2      Anil   22     92  True
3     Priya   20     88  True

In [27]:
df.head()

       Name  Age  Marks  Pass
0  Abhishek   20     85  True
1     Rahul   21     78  True
2      Anil   22     92  True
3     Priya   20     88  True

In [28]:

df.tail()

       Name  Age  Marks  Pass
0  Abhishek   20     85  True
1     Rahul   21     78  True
2      Anil   22     92  True
3     Priya   20     88  True

In [29]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url)

print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [30]:
print("Shape:", df.shape)
print("Columns:", df.columns)

Shape: (150, 5)
Columns: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')